# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

reviews:
  profile: chill
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
    ignore_usernames: ["rapids-bot", "GPUtester", "nv-automation-bot", "copy-pr-bot"]
  tools:
    markdownlint:
      enabled: true
    shellcheck:
      enabled: true
    gitleaks:
      enabled: true
  sequence_diagrams: false
